/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Bitmap;



import javax.imageio.ImageIO;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.awt.image.Raster;
import java.io.File;
import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;

public class App {

    public static void main(String[] args) {


        // get user input image path
        Path inFile = Paths.get("src/main/resources/mario.bmp");
        // get user input path where the altered images will be saved
        //Path outFile = Paths.get(args[1]);
        // get user input for what type of image mutation
        //String imageMutationType = new String(args[2]);



        File inputImageFile = new File(inFile.toUri());

        try {
            BufferedImage image = ImageIO.read(inputImageFile);

            BitMap bmp = new BitMap(image);

            bmp.setInverted();
            bmp.saveImg();



        } catch (IOException e) {
            e.printStackTrace();
        }

    }

}
